### ISSUE TITLE
在谷歌浏览器中测试PWA消息推送node.js连接超时

### ISSUE THREAD

**Issue by missgentle** [missgentle/hello-world#6]
前台log显示
Fetch failed loading: POST "http://localhost:8088/register".
再看服务器端log，哇~又是一个新的报错：
{ Error: connect ETIMEDOUT 74.125.204.95:443  （或是108.177.125.95:443）
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
  code: 'ETIMEDOUT',
  errno: 'ETIMEDOUT',
  syscall: 'connect',
  address: '74.125.204.95',
  port: 443 }
这是什么鬼啊？什么东西连接超时？上网查查。。。

**Comment by missgentle** [comment]
只找到一篇情况很像的问题描述：request模块 ETIMEDOUT 的问题？没有解决方案的回答，但据此初步判断是web-push的使用有问题，毕竟我的项目转成ts了但贴过来的是js代码。既然是web-push有问题，那先去看看npm上的官文，结果没有什么特别的发现。但接下来在网上看到了两篇文章：https://segmentfault.com/a/1190000013061924
http://blog.selfup.cn/1846.html
心里不是滋味。因为发现消息推送原来还要依赖“推送服务器”。
概括来说：Web Notifications是html5定义的一套api接口，主要用来询问是否允许消息通知、展示消息通知等。目前主流浏览器中，只有firefox、chrome、safari、opera支持。应用服务器发送web push协议标准的api，触发推送服务器的消息推送，其中headers必须配置正确，且传送的数据必须是比特流。应用服务器发送消息推送请求（目的是为了将更新推送到用户的浏览器），为了向推送服务器发出请求，需要查看先前获得的PushScription，取出其中的endpoint，即为推送服务器配置给该用户的访问点。而推送服务器的不可选择性，在调用subscribe生成PushScription时，浏览器会向它指定的中转服务器发送请求来生成endpoint和其余部分，这是没法控制的。
在chrome浏览器得到注册信息：
{"endpoint":"https://fcm.googleapis.com/fcm/send/eMuYq-yPoCo:APA91bEYlS-C4ZbHsxGv3yIrAom0xunrhinsaeUxjRuCdqXHAP318CeaG9Vd59RP9pMgvd9NzeJ91YyYK4jn5Qtf4EPL-w3T477SN2AcZn-NTEPTdvEyTfo0tqzTokEhJMamTW5L4AI_","expirationTime":null,"keys":{"p256dh":"BGVJc7QDZ8zeUQpsD1LysjWWORIeaMKZGyjGFmskMwyZjC7zlrjza1WY_lVtZRtABTVzGRgadgUJJfxSBzr3TnY=","auth":"TOwZrP5ZlmqeCoLrkoE2ag=="}}
在firefox，则得到注册信息：
{"endpoint":"https://updates.push.services.mozilla.com/wpush/v2/gAAAAABZ6artFSCkX6LKbHPtfa70_Hs7KzyZNvI-WsGFVe0PXXk4EL2iUDsOmZQbhjgkWzNgqsu9SHZEcysis8kHvS1YcPt6cPX9ysXAHvl6DWkTDVwIMwnEE63sX1oOWQyejRzhoN1J2uZQoXj2tCpXJOLylYkgY3wj9oeGsyrdnlq7ATaNQcE","keys":{"auth":"nE1k27BI12z-le8bfC2SRQ","p256dh":"BD37FPBUEN7814MGzGSCRSEUbGOAnQ-cz0GxvCkVRr95M2qh-j9UN-5ab2hj9YtxcYjMdEpzd5nu2Wd8RYee-Zc"}}
现在看来后台连接超时很可能是因为https://fcm.googleapis.com/fcm/send被墙了。
果然在火狐中是可行的。
